services:
  sql_server_arq_capas:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_arq_capas
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password2026
      MSSQL_PID: Express
    ports:
      - 1402:1433
    volumes:
      - C:\Docker\Volumenes\layared_volumen:/var/opt/mssql/data
    networks:
      - layared_network

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=Password2026
    ports:
      - 5341:80
    volumes:
      - C:\Docker\Volumenes\seq_volumen:/data
    networks:
      - layared_network

  em-pedidos-ui:
    build:
      context: .
      dockerfile: dockerfile
    image: em.pedidos.ui:1.0.0
    container_name: em-pedidos-ui
    restart: always
    ports:
      - "1400:80"
    networks:
      - layared_network

networks:
  layared_network:
    driver: bridge
